# Cloud Run YAML Reference https://cloud.google.com/run/docs/reference/yaml/v1
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-github-actions # Replace with your Cloud Run Service Name
  labels:
    cloud.googleapis.com/location: "asia-southeast1"
  annotations:
    run.googleapis.com/ingress: "all"
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 0
        autoscaling.knative.dev/maxScale: 3
        run.googleapis.com/startup-cpu-boost: false
        #run.googleapis.com/vpc-access-connector: SERVERLESS_VPC_CONNECTOR
        #run.googleapis.com/vpc-access-egress: EGRESS
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: "cloudrun-sa@nuttee-lab-02.iam.gserviceaccount.com"
      containers:
      - image: service-image # Replace with built image
        name: cloud-run-github-actions # Replace with your container name
        env:
        - name: TARGET
          value: "World!"
        resources:
          limits:
            cpu: 1
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /
            #port: 8080
          #initialDelaySeconds: 0
          #timeoutSeconds: 1
          #failureThreshold: 3
          #periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            #port: 8080
          #initialDelaySeconds: 0
          #timeoutSeconds: 1
          #failureThreshold: 3
          #periodSeconds: 10