# This workflow build and push a Docker container to Google Artifact Registry and deploy it on Cloud Run when a commit is pushed to the $default-branch branch
#
# Overview:
#
# 1. Authenticate to Google Cloud
# 2. Authenticate Docker to Artifact Registry
# 3. Build a docker container
# 4. Publish it to Google Artifact Registry
# 5. Deploy it to Cloud Run
#
# To configure this workflow:
#
# 1. Ensure the required Google Cloud APIs are enabled:
#
#    Cloud Run            run.googleapis.com
#    Artifact Registry    artifactregistry.googleapis.com
#
# 2. Create and configure Workload Identity Federation for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Ensure the required IAM permissions are granted
#
#    Cloud Run
#      roles/run.admin
#      roles/iam.serviceAccountUser     (to act as the Cloud Run runtime service account)
#
#    Artifact Registry
#      roles/artifactregistry.admin     (project or repository level)
#
#    NOTE: You should always follow the principle of least privilege when assigning IAM roles
#
# 4. Create GitHub secrets for WIF_PROVIDER and WIF_SERVICE_ACCOUNT
#
# 5. Change the values for the GAR_LOCATION, SERVICE and REGION environment variables (below).
#
# NOTE: To use Google Container Registry instead, replace ${{ env.GAR_LOCATION }}-docker.pkg.dev with gcr.io
#
# For more support on how to run this workflow, please visit https://github.com/marketplace/actions/deploy-to-cloud-run
#
# Further reading:
#   Cloud Run IAM permissions                 - https://cloud.google.com/run/docs/deploying
#   Artifact Registry IAM permissions         - https://cloud.google.com/artifact-registry/docs/access-control#roles
#   Container Registry vs Artifact Registry   - https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry
#   Principle of least privilege              - https://cloud.google.com/blog/products/identity-security/dont-get-pwned-practicing-the-principle-of-least-privilege


name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - staging
      - dev

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  PROJECT_ID: nuttee-lab-02 # YOUR_PROJECT_ID # TODO: update Google Cloud project id
  GAR_LOCATION: asia-southeast1 # YOUR_GAR_LOCATION # TODO: update Artifact Registry location
  REPOSITORY: github-actions # YOUR_REPOSITORY_NAME # TODO: update Artifact Registry repository name
  CICD_PROJECT_ID: nuttee-lab-tf
  # Cloud Run YAML reference https://cloud.google.com/run/docs/reference/yaml/v1
  #SERVICE_NAME: cloud-run-github-actions # YOUR_SERVICE_NAME # TODO: update Cloud Run service name
  #DESCRIPTION: 'cloud run github actions example'
  #REGION: asia-southeast1 # YOUR_SERVICE_REGION # TODO: update Cloud Run service region
  #SERVICE_ACCOUNT_EMAIL: cloudrun-sa@nuttee-lab-02.iam.gserviceaccount.com # YOUR_SERVICE_ACCOUNT_FOR_CLOUD_RUN # TODO: update Cloud Run Service Account

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com  
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 437.0.0'
        install_components: 'beta,alpha,skaffold'

    # Authenticate Docker to Google Cloud Artifact Registry
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v2'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

    # Git shart SHA
    - name: Git short SHA
      id: short-sha
      run: |-
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$calculatedSha"

    # Run skaffold build
    - name: Skaffold run (build and deploy) PROD
      id: skaffold-build-dev
      if: contains(github.ref, 'dev')
      run: |-
        skaffold build -p dev --file-output=output-${{ steps.short-sha.outputs.short_sha }}.json
    
    # 
    - name: Upload Skaffold build file output to GCS
      id: 'upload-skaffold-build-file-output'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'output-${{ steps.short-sha.outputs.short_sha }}.json'
        destination: '${{ env.CICD_PROJECT_ID }}-skaffold/output-${{ steps.short-sha.outputs.short_sha }}.json'

    # Run skaffold run
    - name: Skaffold run (build and deploy) PROD
      id: skaffold-prod
      if: contains(github.ref, 'main')
      run: |-
        skaffold run -p prod
    
    - name: Skaffold run (build and deploy) STAGING
      id: skaffold-staging
      if: contains(github.ref, 'staging')
      run: |-
        skaffold run -p staging
    
    - name: Skaffold run (build and deploy) DEV
      id: skaffold-dev
      if: contains(github.ref, 'dev')
      run: |-
        skaffold run -p dev

    #- name: Build Container
    #  run: |-
    #    docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" ./
        
    #- name: Push Container
    #  run: |-
    #    docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

    #- name: Deploy to Cloud Run
    #  id: deploy
    #  uses: google-github-actions/deploy-cloudrun@v1
    #  with:
    #    service: ${{ env.SERVICE_NAME }}
    #    region: ${{ env.REGION }}
    #    project_id: ${{ env.PROJECT_ID }}
    #    flags: '--service-account=${{ env.SERVICE_ACCOUNT_EMAIL }} --cpu=1 --memory=512Mi --max-instances=3 --concurrency=100 --ingress=all --allow-unauthenticated'
    #    # NOTE: If using a pre-built image, update the image name here
    #    image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
    #    # NOTE: You can also set env variables here:
    #    #  env_vars: |
    #    #  NODE_ENV=production
    #    #  TOKEN_EXPIRE=6400